
[client]
showSidebarNavigation = false



[server]
address = "0.0.0.0"
port = 8502
headless = true

# .streamlit/config.toml
[theme]
base = "light"                     # or "dark"
primaryColor = "#0014DC"           # buttons, accents, widgets
textColor = "#0014DC"              # ALL body text & headings
# Optional (tune to your brand if you change backgrounds)
# backgroundColor = "#FFFFFF"
# secondaryBackgroundColor = "#F5F7FF"
