
OSDU_BASE_URL = "https://eu6.api.enterprisedata.slb.com"
DATA_PARTITION_ID = "mlc-training"
APPKEY = "YOUR_APP_KEY"

TOKEN_URL = "https://csi.slb.com/v2/token"
CLIENT_ID = "9acad4eaff2a2768b2696fff83a3adff"
CLIENT_SECRET = "d41829420ce44264b826516e56b35fd2ba43e9e6cde08ac1"
SCOPE = "963f2cc6915e479fa0fcb73ec2ec90e7"

WORKFLOW_NAME = "csv_parser_wf"


ACL_OWNER = "data.dm-pj-af93f9e8-98e1-45d3-a2f2-d5515d5b4669.owners@mlc-training.enterprisedata.slb.com"
ACL_VIEWER = "data.dm-pj-af93f9e8-98e1-45d3-a2f2-d5515d5b4669.viewers@mlc-training.enterprisedata.slb.com"
LEGAL_TAG = "mlc-training-referencedata-legal"

WORKFLOW_STATUS_PATH_TMPL = "/api/workflow/v1/workflow/{workflow_name}/workflowRun/{run_id}"